# Generated by Django 6.0.5 on 2026-05-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="premium_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
