# Generated by Django 6.0.4 on 2026-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=70)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("mers", "MERS"),
                            ("bmw", "BMW"),
                            ("audi", "AUDI"),
                            ("boshqa", "BOSHQA"),
                        ],
                        default="boshqa",
                        max_length=50,
                    ),
                ),
                ("year", models.DateField()),
                ("max_speed", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
