# Generated by Django 6.0.5 on 2026-05-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
