# Generated by Django 6.0.4 on 2026-04-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=40)),
                ("subject", models.CharField(max_length=40)),
                ("experience", models.PositiveIntegerField()),
                ("age", models.PositiveIntegerField()),
            ],
        ),
    ]
